[site]
title = "Aziz Ebrahimi"
description = "Academic website of Aziz Ebrahimi, Assistant Professor of Forest Genetics, Genomics & Tree Breeding."
favicon = "/favicon.svg"
last_updated = "September 2, 2026"

[author]
name = "Aziz Ebrahimi"
title = "Assistant Professor of Forest Genetics, Genomics & Tree Breeding"
institution = "Warnell School of Forestry and Natural Resources, University of Georgia"
avatar = "/avatar.svg"

[social]
# Contact information (leave blank or delete to hide)

email = "aebrahimi@purdue.edu"
location = "Athens, Georgia, USA"
location_url = ""
location_details = [
  "Warnell School of Forestry and Natural Resources",
  "180 East Green Street, Building 4, Room 530",
  "Athens, GA 30602"
]
google_scholar = "https://scholar.google.com/citations?user=zxhKlXMAAAAJ&hl=en"
orcid = "https://orcid.org/0000-0003-3122-0404"
github = ""
linkedin = "https://www.linkedin.com/in/aziz-ebrahimi-7932b152/"
researchgate = "https://www.researchgate.net/profile/Aziz-Ebrahimi"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, the website will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research"
type = "page"
target = "research"
href = "/research"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Team"
type = "page"
target = "team"
href = "/team"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
